### ISSUE TITLE
刷不出hkg

### ISSUE THREAD

**Issue by MirrorCY** [Windla/WARP-PLUS-HKG#1]
怎么刷都是SJC，想连HK做游戏加速捏

**Comment by MirrorCY** [comment]
中午的时候挂ss后打开warp会尝试连HKG，但是怎么也连不上。晚上就不行了，直接不去连HK了

**Comment by Windla** [comment]
> 中午的时候挂ss后打开warp会尝试连HKG，但是怎么也连不上。晚上就不行了，直接不去连HK了

好刷 要刷的时候记得
1. 打开warp的开关 2. (尝试)不要挂梯 3. 弹出管理员要给(仅用于重启warp-svc服务)

首先确保自己在裸连情况下可以连的上warp的服务器
然后先看看trace(下面链接)里对于warp的描述,确保为(warp=on/plus)(即连接上了warp服务器）

这玩意的原理是检测 https://1.1.1.1/cdn-cgi/trace 中对于colo和warp的内容
通过多次重连来刷HKG

HKG的话主要是看warp想连哪个 我个人觉得是玄学
但是连上了SJC后 第二次连接大概率就是HKG
(和你的网络地理位置也有相关)
